kind: ENC[AES256_GCM,data:QvXXUqZ6,iv:U20U5b/DjRlcE7ouup26E16NIHHbrBeOBvCKP8mm3xo=,tag:2gNaqRiUfWjrAUI2pBchdQ==,type:str]
ansible_user: ENC[AES256_GCM,data:9rnGGsKHVA==,iv:/r2JdA6JHrhvfq+gCCcgSjcG3Nu4f/2Pe/xdToG7NZE=,tag:F9PjIw/S6Q+tB9Vkp6GG1Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:1yLpTpLKUw==,iv:BsIQGsM9IkMgONQbw+EVC3SUYvOqriVhnTZhUzhcjvA=,tag:sE1qizBVH5XNoDoz7fTrpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vmpeqdyf2xwqqywrzqwq68puuw7dhlgadxh8v4pw40ae8fmu8a6snclmde
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M2l5czNUNmZkeHh1dkox
            ak83TVpaQnNFNDZPSFdRbzd2eVpZVENjZXo4ClJOWGxLTnpxMkt0N0R4WG1kMFZD
            OGZtOWJkQ2liZVgybXpFTGs3b25sL2cKLS0tIDlzQXZJOWYzMmd0ZXdjRk5QSWhX
            Y3hsM3lUay9NYlluSmZQNUlwamgwbUEKebR4fRpvPc3LecT5wBdKMNs1BU+HY0V0
            Fq4FnEWI0C/0KRNZAjFgptv2JvZRFWjbOhG0BRv/90l2pm2Zi4ak6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T08:07:47Z"
    mac: ENC[AES256_GCM,data:PV8PL5PQ38btEMRty1DqQH5CFCyB3QbvbGg6Ui0/QSsER4k8svE987gVPqgI1l0NF303E2C1yETjndWDSpr5ETmjwcH5oE51yvZx2E7JGctma9PnIzIJKw2xXt/93GD8pf1Ih4iZu2pxubrS08+qjSmBnBvTTBSLB6f3OX1bsrc=,iv:BoqEAnTNclWg5YCo8ILhhHyz2lYr3L7NCwYWi0fFMFQ=,tag:BJACwS5FSqh0DRjSqZNOdg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
