apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:PyTLelwff8ErgDASKBqNJxcXvvEq494lQPLp9WfS59AxRUka2syFEA==,iv:PXaGkD3JLmxpAaUNDyJPqXB8iHxnUdtmuSVfQ8FAHy8=,tag:uw2odhZ5MTqlPAzmFnnb3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vmpeqdyf2xwqqywrzqwq68puuw7dhlgadxh8v4pw40ae8fmu8a6snclmde
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT1M5andQaEFOZkk2d2dr
            R0xud2hpMEhGMjZjUDcrQ1ptOEE2ZXkvSXdZCm1UemNJQmFPdVQvWlNuM3JzQnNp
            d25iMVlDY0R1UVhVUW5GekhwN2dLUGsKLS0tIFJzaVBtaW85QW1nRkFpeEFBV2Z3
            SkxDT1k1OXllaXRkV05yYXBna3VReGMK6OT+Ma8GgE4aWEKwnM8UDfA1RBKb0dwH
            vEgl4f5b9Bsg3JogthnITMCqFxOMndNcrkBgsLXILrk95TGf57xfjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T05:22:03Z"
    mac: ENC[AES256_GCM,data:eqNJ9B3/SPN5MbmptonXYMAjH8+D4LmVKAaFf28EhHdo1srH9ztzbhG51iKbXLqCZoS6nt+0nsrhVg1n9kqd7EoH1KzUqsX/sH1+e6bamh5eCB5V+BqSHeaXfEaGUfKbahTvFIgfxHyvz1x8FDKqNHnCbLRYI9zlXafdq5lwf9Q=,iv:/YSsDXgMgF+Rco5RSh64kjsV2VWtkFLuUFDfzR/ytlg=,tag:1x1CKNNeb28X48MulXcycg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
