---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.10.50.110
    worker:
      hosts:
        k8s-1:
          ansible_host: 10.10.50.111
        k8s-2:
          ansible_host: 10.10.50.112
