apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Ob+ofCuqM5NWP0PGvBYAJpFK43505c7s6yIekJy4E+inz3MlAg==,iv:lqLX+DRs+RcZgVBXGVLr4ty5JAAszWwpI6E51aL/cQ8=,tag:zEzL2NuCj3uCQ7O+3zPcNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vmpeqdyf2xwqqywrzqwq68puuw7dhlgadxh8v4pw40ae8fmu8a6snclmde
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN040eXJvOE9wQWJXc1lm
            cndUVmRWYUhIZXhZL24yY2x4V1Q1N3FraXdNCmFodXZJbkwwSisvVTNDUWpuMVJG
            MUl5RjZVaytGMWF0STl4MHZVR3JES2sKLS0tIGhOeWU1YnhhNkZ6aXcvanRFZ2tF
            Y24zNkNEazRtN1lKTUZRTTZzZTJiajAKIGff1TfcIBx4VPddRz72bFI1ahO8D0Zi
            EEOuTa9zUvFfByZSTedhBUIZYpTTUaRVan7z8ACYa7+DxM0FVIENbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T08:07:46Z"
    mac: ENC[AES256_GCM,data:V1sqWBfKH685b2uHVGofynB38X3VtD5pBO9mno61oaS52Aa0vgmiSGlF83lOUDeqSHAfiBI5ZlNOPq0YidpXVhFnybCCWs397ZtcFma/K93lENjRJztpfXh7Cmo1H3nd6qePQsmZGdzHjXkGhjOluo20D0bMx37mX8KBPkwNQ20=,iv:IP27MAVG67PiGZs4TqLFuwi5ZcMqAyQYR0qNEj4kiec=,tag:Sb9wTlXCcgCNrqLGFzTUlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
