apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:xlcLtohJcwJeDWBhSzpwrr+77QL7I7inv1yzwfXocV9nO+CnIzRxYEN3GgdCaIvALZiAIm8uQLnnxtqM,iv:1o5MNo1/FZTWUUBseUnEAwLBk40z+3eVAY0mTGxnXEE=,tag:nd6BhzLqHI5ztwXbBqHNWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vmpeqdyf2xwqqywrzqwq68puuw7dhlgadxh8v4pw40ae8fmu8a6snclmde
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eEhUNG1hUmwwRkUvbTdn
            cXc0QTdpUjlFQXRpRnJtK0ZlbnpMMWlYeEZ3CmtKbUFYcXBnRlZ3R3BNU3ZuWlhJ
            VzhlcXlOUDlUdW12ZGg0UE52aEdBZTQKLS0tIGdVZjM0OFRyU3RzVll5TWllQnVt
            L210eWVuZS9xUzZCK2V5U1BLMzVBNFEKDYNcaN8NFlDHwnuRxpFLH+1A0kOo7OZ2
            xUtMHZC+SSNLYX69g4UaF5K8/xRl7ugEbNZn8JA+ct51HJrXulTzfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T05:22:08Z"
    mac: ENC[AES256_GCM,data:kIUpL1p/lETBZ++o3PsKE7PwN3Cz/QM8hr6BI1L3gt41k2LA5XK0bTjJ+syxqYzso6ePnB1VkbHmYk+Jr8sGmqso7GKJDlLijzkaHlS+kIK0cGXl6PGthBjQ67gUZkZWlS2EMDpXR7Suw2fV1NZrchNG8LmNCggciyMai+0FALM=,iv:kFw6idxRQg77gpw3ugIZ+c1ZOaGJVxtuvcPOFL5vaHc=,tag:61TPhsOlOD6jU1tfEXq+cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
