---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "10.10.50.231"
  METALLB_LB_RANGE: "10.10.50.220-10.10.50.230"
  METALLB_K8S_GATEWAY_ADDR: "10.10.50.220"
  METALLB_INGRESS_ADDR: "10.10.50.221"
