---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-operator
  namespace: monitoring
spec:
  chart:
    spec:
      chart: starboard-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
      version: 0.10.3
  interval: 1m0s
